name: GitHub checks

on:
  push:
    - "**"

jobs:
  check_web:
    name: Check Python

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -r requirements.lock
        pip install -r requirements-dev.lock

    - name: Run Tests
      run: |
        python3 manage.py test

    - name: Run MyPy to check typing
      run: |
        python3 manage.py test

    - name: Run isort to order imports
      run: |
        python3 isort

    - name: Run Black to enforce code style
      run: |
        python3 black
        